# Generated by Django 4.0.3 on 2022-04-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0002_author_category_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
