# Generated by Django 4.0.3 on 2022-04-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0003_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
