# Generated by Django 4.0.3 on 2022-04-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_library', '0004_book_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
